feat: project framework and programming specifications
pikiwidb/pika-proxy pull request #7
Opened 2023-07-02 10:49 UTC by yaoyinnan

1. Sort out the framework of the functions that need to be implemented
2. Discuss the programming specification of the project through PR. Including but not limited to:
    1. Error handling
    2. Logs
    3. Generics
    4. Lifetimes
    5. Asynchrony (tokio + async)

Fixes: #6

2023-07-02 12:13 UTC, Tangruilin commented on src/proxy/config.rs
> +    fn read_from_file(path: &str) -> ProxyResult<Config> {
这里我认为不需要 Result，我之前没写的理由很简单：如果 Config 获取失败了，程序应该直接 panic，服务不需要继续启动了，这里应该看做启动失败

2023-07-02 12:13 UTC, Tangruilin commented on src/proxy/proxy.rs
> +async fn do_task(stream: TcpStream) {
不是 mut 的stream 应该是没法做写操作的吧，这个编译器能过吗？

2023-07-02 12:13 UTC, Tangruilin commented on src/proxy/router.rs
> +pub struct Router {}
这里建议实现成 接口，因为路由规则我们后续可能拓展，Router 本身应该是一个接口而不是 struct

2023-07-02 12:13 UTC, Tangruilin commented on src/proxy/router.rs
> +pub struct Router {}
另外这里的命令修改一下，_fill_slot 这种改成 fill_slot 然后不加 pub 就行了

再就是 dyn 改成泛型参数，不用接口表示

2023-07-02 12:13 UTC, Tangruilin commented on src/proxy/session.rs
> +    pub stream: TcpStream,
不要删除 (crate)，后面风格统一定下来

pub(crate)
pub(super)表示的意义是不一样的

2023-07-02 12:13 UTC, Tangruilin commented on src/proxy/session.rs
> +    pub fn new(option: SessionOption) -> Self {
不要这么改
new 方法是不需要参数的
参考 rust 的默认类型

2023-07-02 12:13 UTC, Tangruilin commented on src/proxy/session.rs
> +    pub fn new(option: SessionOption) -> Self {
String::new()
String::from("abc")

2023-07-02 12:13 UTC, Tangruilin commented on src/proxy/session.rs
> +    fn string(&self) -> String {
这里要用 string 就改成 to_string

2023-07-02 12:13 UTC, Tangruilin commented on src/utils/error.rs
> +pub enum ProxyError {
错误不能这样划分的，这样划分太细了，抽象程度太低，具体的错误类型到时候整理好商量，最终不要超过7种

2023-07-02 12:19 UTC, Tangruilin commented
我给了一版意见。
总结一下几个问题：
1. 错误划分的时候要注意抽象，比如：1. IO错误；2. 参数校验错误； 3. 网络错误； 4. 未知错误； 不要搞十几个错误类型，这样大家会去随便补充的，错误类型是不应该动的；
2. 设计数据结构的时候考虑好其中的成员是否需要在多线程中使用，同时要考虑是否使用 move 语义，结构体中使用 move 语义，如果在多线程环境是很难处理生命周期的， 需要多线程的变量用 Arc 包一下；
3. 抽象数据的设计问题。codis 中有些成员比如 Router 设计成了结构体，但是我们不确定以后路由方式会不会重构，因此这种接口处的东西全部设计为 Trait，不要使用具体的结构体，方便后续进行升级等操作。包括但不限于： Session， Router，Conn 这类，这些我们需要考虑清楚，不要随手写

2023-07-02 12:21 UTC, Tangruilin commented
> 我给了一版意见。 总结一下几个问题：
> 
> 1. 错误划分的时候要注意抽象，比如：1. IO错误；2. 参数校验错误； 3. 网络错误； 4. 未知错误； 不要搞十几个错误类型，这样大家会去随便补充的，错误类型是不应该动的；
> 2. 设计数据结构的时候考虑好其中的成员是否需要在多线程中使用，同时要考虑是否使用 move 语义，结构体中使用 move 语义，如果在多线程环境是很难处理生命周期的， 需要多线程的变量用 Arc 包一下；
> 3. 抽象数据的设计问题。codis 中有些成员比如 Router 设计成了结构体，但是我们不确定以后路由方式会不会重构，因此这种接口处的东西全部设计为 Trait，不要使用具体的结构体，方便后续进行升级等操作。包括但不限于： Session， Router，Conn 这类，这些我们需要考虑清楚，不要随手写；
4. 对应初始化方法的选择，参考标准库的写法，尽量不要基于过往经验；ps: 关于 from 的初始化方式，委员会之所以只设计了一个入参，我的考虑是，他是借鉴了C++ 常用的初始化方案，Option + 具体类，不要搞太多的初始化函数。另外 new 函数是不带参数的，既然标准库给了初始化的标准方案，那就按照标准库的方案来

2023-07-03 01:58 UTC, Dennis-Zhang-SH commented on src/models/proxy.rs
> +            start_time: String::new(),
Chrono datetime or a simple int64 would be better?

2023-07-03 01:58 UTC, Dennis-Zhang-SH commented on src/models/proxy.rs
> +            admin_addr: String::new(),
If this is a ip address, better using IpAddr instead of a string.

2023-07-03 01:58 UTC, Dennis-Zhang-SH commented on src/models/proxy.rs
> +            proto_type: String::new(),
Add a enum of proto_type?

2023-07-03 01:58 UTC, Dennis-Zhang-SH commented on src/models/proxy.rs
> +            proxy_addr: String::new(),
Same as before

2023-07-03 05:31 UTC, infdahai commented on src/models/proxy.rs
> +            start_time: String::new(),
Maybe chrono::DateTime<Utc>?

2023-07-03 05:31 UTC, infdahai commented on src/models/proxy.rs
> +            admin_addr: String::new(),
Maybe std::net::SocketAddr?

2023-07-03 05:31 UTC, infdahai commented on src/models/proxy.rs
> +        serde_json::to_vec(self).unwrap()
Maybe bytes::BytesMut?

2023-07-03 05:32 UTC, infdahai commented
Perhaps I think we should write basic comments for the underlying structs.

2023-07-03 10:46 UTC, Aya0wind commented
> 不要这么改
new 方法是不需要参数的
参考 rust 的默认类型 

new可以有参数吧，标准库的Cell，Box这些都是有参数的，规定无参数的话那跟Default功能就重了，需要有参数是没问题的

2023-07-03 12:24 UTC, Aya0wind requested changes

2023-07-23 11:23 UTC, yaoyinnan commented
重新调整了架构，#32 做了新的框架的拆分。

2023-07-23 11:23 UTC, closed without merging